application: anceont
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /s
  static_dir: s

- url: /file
  script: file.application

- url: /.*
  script: anceont.application
